---
- hosts: localhost
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elasticsearch }
    - { role: logstash }
    - { role: nginx }
    - { role: kibana }
    - { role: xpack, when: ((install_elasticsearch_xpack) or (install_kibana_xpack) or (install_logstash_xpack)) }
    - { role: firewall, when: manage_firewall }
    - { role: instructions }
